### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by cyb3rjerry** [edoardottt/cariddi#88]
**Describe the bug**
After a while we (for some reason) get a slice out of bounds errors
```
goroutine 25981 [running]:
github.com/edoardottt/cariddi/pkg/crawler.New.func15(0xc072bd1380)
	/opt/hacking/repository/cariddi/pkg/crawler/colly.go:215 +0x950
github.com/gocolly/colly.(*Collector).handleOnResponse(0xc072bd1380?, 0xc072bd1380)
	/home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:936 +0x1be
github.com/gocolly/colly.(*Collector).fetch(0xc00018d520, {0x0?, 0x0?}, {0x8c1eaa, 0x3}, 0x1, {0x0?, 0x0}, 0x0?, 0xc0304a96e0, ...)
	/home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:621 +0x69b
created by github.com/gocolly/colly.(*Collector).scrape
	/home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x645
```

**To Reproduce**
1. run `echo "https://mapbox.com/" | cariddi -s  -intensive`

**Desktop (please complete the following information):**
Linux cyb3rjerry 5.19.0-23-generic 24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by edoardottt** [comment]
Line 215 is `FinalSecrets = append(FinalSecrets, secretsSlice...)`

This was the error I was referring to :/ I don't know why honestly

**Comment by cyb3rjerry** [comment]
I'll dig a little more into this to better understand what exactly is going on

**Comment by cyb3rjerry** [comment]
So after thinkering on this I'm starting to think this is a concurrency issue. Cariddi is **highly** concurent so we might actually want to enforce atomicity with mutexes
Result of `echo "https://google.com | go run -race ./cmd/cariddi/main.go`

```
==================
WARNING: DATA RACE
Read at 0x00c0147a92f0 by goroutine 819:
  github.com/gocolly/colly.(*Collector).isDomainAllowed()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:680 +0xc66
  github.com/gocolly/colly.(*Collector).scrape()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:503 +0x145
  github.com/gocolly/colly.(*Collector).Visit()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:412 +0xee
  github.com/edoardottt/cariddi/pkg/crawler.visitHTMLLink()
      /tmp/cariddi/pkg/crawler/colly.go:385 +0x20b
  github.com/edoardottt/cariddi/pkg/crawler.New.func4()
      /tmp/cariddi/pkg/crawler/colly.go:139 +0x1e4
  github.com/gocolly/colly.(*Collector).handleOnHTML.func1()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:963 +0xdb
  github.com/PuerkitoBio/goquery.(*Selection).Each()
      /home/cyb3rjerry/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteration.go:10 +0x61
  github.com/gocolly/colly.(*Collector).handleOnHTML()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:953 +0x4db
  github.com/gocolly/colly.(*Collector).fetch()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:623 +0xc5c
  github.com/gocolly/colly.(*Collector).scrape.func1()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x10b

Previous write at 0x00c0147a92f0 by goroutine 12:
  github.com/edoardottt/cariddi/pkg/crawler.New.func16()
      /tmp/cariddi/pkg/crawler/colly.go:301 +0x1d1

Goroutine 819 (running) created at:
  github.com/gocolly/colly.(*Collector).scrape()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0xb19
  github.com/gocolly/colly.(*Collector).Visit()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:412 +0xee
  github.com/edoardottt/cariddi/pkg/crawler.visitXMLLink()
      /tmp/cariddi/pkg/crawler/colly.go:408 +0x20b
  github.com/edoardottt/cariddi/pkg/crawler.New.func9()
      /tmp/cariddi/pkg/crawler/colly.go:169 +0x1a5
  github.com/gocolly/colly.(*Collector).handleOnXML.func1()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:1020 +0x37b
  github.com/antchfx/xmlquery.FindEach()
      /home/cyb3rjerry/go/pkg/mod/github.com/antchfx/xmlquery@v1.3.10/query.go:136 +0x85
  github.com/gocolly/colly.(*Collector).handleOnXML()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:1012 +0x554
  github.com/gocolly/colly.(*Collector).fetch()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:628 +0xca4
  github.com/gocolly/colly.(*Collector).scrape.func1()
      /home/cyb3rjerry/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x10b

Goroutine 12 (running) created at:
  github.com/edoardottt/cariddi/pkg/crawler.New()
      /tmp/cariddi/pkg/crawler/colly.go:289 +0x3174
  main.main()
      /tmp/cariddi/cmd/cariddi/main.go:124 +0x251e
==================
```

**Comment by cyb3rjerry** [comment]
Ok so I actually went a little deeper and can confirm there's a data race on line 215 (in my case it's shown as 216 but it's actually `FinalSecrets = append(FinalSecrets, secretsSlice...)` that got bumped down a line because of some modifications I made)

```
WARNING: DATA RACE
Read at 0x00c000134798 by goroutine 7:
  github.com/edoardottt/cariddi/pkg/crawler.New.func15()
      /home/cbrisson/github/cariddi/pkg/crawler/colly.go:216 +0x274
  github.com/gocolly/colly.(*Collector).handleOnResponse()
      /home/cbrisson/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:936 +0x35c
  github.com/gocolly/colly.(*Collector).fetch()
      /home/cbrisson/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:621 +0xc47
  github.com/gocolly/colly.(*Collector).scrape.func1()
      /home/cbrisson/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x10b
```

**Comment by edoardottt** [comment]
Yeah, it makes sense. But this data race doesn't happen if the FinalSecrets = append(FinalSecrets, secretsSlice...) is replaced with the range loop.

I'm going to go back to the range loop for now as a fast fix.

**Comment by cyb3rjerry** [comment]
Sounds good! I'll start working on a fork that handles everything in a more "controlled" fashion in the mean time :)
